project:
  type: book
  output-dir: docs

book:
  title: "FinCatch Documentation"
  output-file: "FinCatchDocumentation"
  author: "Keith Hurley et al"
  date: "`r format(Sys.time(), '%B %d, %Y')`" 
  chapters: 
    - index.qmd
    - part: intro.qmd
    - part: FinCatchAnalysis_0.qmd
      chapters:
        - FinCatchAnalysis_1_Objects.qmd
    - part: references.qmd
  number-depth: 2
  toc-depth: 2
  bibliography: references.bib

format:
  html:
    theme: slate
  pdf:
    documentclass: scrreprt

editor: visual

