project:
  type: book
  output-dir: docs

book:
  title: "FinCatch Documentation"
  output-file: "FinCatchDocumentation"
  author: "Keith Hurley et al"
  date: "`r format(Sys.time(), '%B %d, %Y')`" 
  chapters: 
    - index.qmd
    - part: FinCatch System
      chapters: 
        - intro.qmd
        - FinCatch_SamplingRestrictions.qmd
        - FinCatch_DataDesign.qmd
        - FinCatch_Architecture.qmd
        - FinCatch_CreateUser.qmd
    - part: FinCatchDE
      chapters: 
        - FinCatchDE_0_Deployment.qmd
    - part: Analysis R Package
      chapters:
        - FinCatchAnalysis_0.qmd
        - FinCatchAnalysis_DataObject.qmd
        - FInCatchAnalysis_WarningsErrors.qmd
        - FinCatchAnalysis_0_ExampleScript.qmd
        - FinCatchAnalysis_0_BaseObject.qmd
        - FinCatchAnalysis_1_Objects.qmd
        - FinCatchAnalysis_1_Methods.qmd
        - FinCatchAnalysis_2_HelperFunctions.qmd
        - FinCatchAnalysis_3_CreateAnalysis.qmd
    - part: FinCatchAccess_0.qmd
    - part: references.qmd
  # number-depth: 2
  # toc-depth: 2
  # bibliography: references.bib

format:
  html:
    theme: cyborg
  pdf:
    documentclass: scrreprt

editor: visual
